version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: app-db
    restart: always
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: app-redis
    ports:
      - "6379:6379"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
